### ISSUE TITLE
question

### ISSUE THREAD

**Issue by marksev1** [biddster/node-red-contrib-wemo-emulator#1]
Very cool node-red node. Once I buy the Echo Dot or if Mycroft will add integration for Wemo devices I will surely use it. My question is can a device be added multiple "Friendly names". For example: "Turn on the sprinkler/hose/irrigation"?

**Comment by biddster** [comment]
This isn't supported currently, other than wiring the output of multiple wemo nodes into the same flow.

**Comment by marksev1** [comment]
Any plans to support it?

**Comment by biddster** [comment]
Not right now, but if more people chip in here, I'll consider it.

The underlying library I rely on doesn't support it either, in essence it would be the same as adding multiple nodes (albeit cleaner).

**Comment by marksev1** [comment]
Cool. Closing.
