### ISSUE TITLE
Devices not found - Or no MQTT msg was send

### ISSUE THREAD

**Issue by thommycgn** [biddster/node-red-contrib-wemo-emulator#10]
![bildschirmfoto 2017-01-27 um 11 25 44](https://cloud.githubusercontent.com/assets/8251797/22367744/75e78810-e483-11e6-819e-842dc6eb9280.png)
Hi!

The device is listening on Port 39900. 
If I search for devices with alexa: no devices found.

Any Ideas?

Here what netstat says: 
______________________________________
pi@raspberrypi:~/.node-red $ netstat -l 
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:36519                 *:*                     LISTEN     
tcp        0      0 *:5001                  *:*                     LISTEN     
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp        0      0 *:1880                  *:*                     LISTEN     
tcp        0      0 *:1883                  *:*                     LISTEN     
tcp6       0      0 [::]:4050               [::]:*                  LISTEN     
tcp6       0      0 [::]:51826              [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 [::]:33339              [::]:*                  LISTEN     
tcp6       0      0 [::]:1883               [::]:*                  LISTEN     
tcp6       0      0 [::]:39900              [::]:*                  LISTEN     
udp        0      0 *:bootpc                *:*                                
udp        0      0 raspberrypi.fritz.b:ntp *:*                                
udp        0      0 localhost:ntp           *:*                                
udp        0      0 *:ntp                   *:*                                
udp        0      0 *:mdns                  *:*                                
udp        0      0 *:50486                 *:*                                
udp        0      0 *:1900                  *:*                                
udp6       0      0 [::]:dhcpv6-client      [::]:*                             
udp6       0      0 [::]:42547              [::]:*                             
udp6       0      0 raspberrypi.fritz.b:ntp [::]:*                             
udp6       0      0 fe80::2d41:bb55:1b8:ntp [::]:*                             
udp6       0      0 localhost:ntp           [::]:*                             
udp6       0      0 [::]:ntp                [::]:*                             
udp6       0      0 [::]:mdns               [::]:*                             
raw6       0      0 [::]:ipv6-icmp          [::]:*                  7          
Aktive Sockets in der UNIX-Domäne (Nur Server)
Proto RefCnt Flags       Type       State         I-Node   Pfad
unix  2      [ ACC ]     STREAM     HÖRT         11298    @/tmp/dbus-2ueJkNwkq9
unix  2      [ ACC ]     STREAM     HÖRT         11267    /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     HÖRT         9959     /tmp/ssh-lZpzGv7fLPOL/agent.724
unix  2      [ ACC ]     STREAM     HÖRT         11611    /tmp/ssh-IRCIA5ghuP98/agent.1271
unix  2      [ ACC ]     STREAM     HÖRT         12683    /tmp/.pcmanfm-socket--0-pi
unix  2      [ ACC ]     STREAM     HÖRT         11266    @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     HÖRT         5179     /run/systemd/private
unix  2      [ ACC ]     SEQPAKET   HÖRT         5201     /run/udev/control
unix  2      [ ACC ]     STREAM     HÖRT         5205     /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     HÖRT         12757    /tmp/.menu-cached-:0-pi
unix  2      [ ACC ]     STREAM     HÖRT         9673     /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     HÖRT         9675     /var/run/dhcpcd.unpriv.sock
unix  2      [ ACC ]     STREAM     HÖRT         7664     /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     HÖRT         7924     /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     HÖRT         7667     /var/run/dbus/system_bus_socket

**Comment by thommycgn** [comment]
Ok, now after reloading the alexa-app the device is in the list. 
But if I ask alexa to turn the light on/off she just say ok. 
The status is changing to on/off but no mqtt msg was send.

**Comment by biddster** [comment]
Have you tried wiring the output of this wemo node into a debug node and watching in the admin console when you ask alexa to turn on and off? If you set the debug node to dump the entire message we should see your configuration from above. 

Mine has been super reliable for months so there must be something amiss.

**Comment by biddster** [comment]
Having thought about it, I think the fault must lie elsewhere. If the status on this node is changing, it must have emitted a msg via `node.send({topic: config.onTopic, payload: config.onPayload});`.

**Comment by thommycgn** [comment]
Output: 

cmnd/led-deko-lampe/power : msg : Object
{ "topic": "cmnd/led-deko-lampe/power", "payload": "on", "_msgid": "57254bc9.a8dab4" }

But nothing else happen, no mqtt command goes out.

**Comment by biddster** [comment]
This looks like an issue elsewhere in your flow. This node is doing what it is supposed to. I suggest asking on the node red Google group.

**Comment by VillageThing** [comment]
I'm having trouble getting the Alexa app on my iPad to discover the wemo-emulator nodes. I have had them working in the past but at some point in the past month, they have stopped. Alexa won't discover any new instances of the node and existing nodes are listed in the Alexa app as 'offline'.

![node2](https://cloud.githubusercontent.com/assets/18529147/25774161/443381fa-3282-11e7-9432-4b0a917b9eb2.png)

Furthermore, today, I noticed that one of them is showing a error...

![nodes](https://cloud.githubusercontent.com/assets/18529147/25774187/b5861ca0-3282-11e7-8dcc-7bbacd375ca3.png)

Any help much appreciated.

**Comment by biddster** [comment]
Thanks for the report @VillageThing. What version of node-red and nodejs are you using?

**Comment by VillageThing** [comment]
Hi,

Here’s the version details:-

22 May 22:16:04 - [info] Node-RED version: v0.16.2
22 May 22:16:04 - [info] Node.js  version: v4.8.3
22 May 22:16:04 - [info] Linux 4.9.24-v7+ arm LE

**Comment by biddster** [comment]
I'm struggling to find this one @VillageThing. This node doesn't do much other than wrap the wemore library. I'm struggling to find where in wemore that error might be thrown. 

Have you upgraded nodejs since installing this node?

**Comment by VillageThing** [comment]
Thanks for looking. I'd really like to get this working. It's such a useful node. Shall I uninstall the wemo emulator and re-install it?
Keith.

**Comment by biddster** [comment]
By all means give that a try and let me know.

**Comment by biddster** [comment]
Closing old issue as no reply for a couple of years.
