### ISSUE TITLE
Document Firewall Settings

### ISSUE THREAD

**Issue by katterfelto** [biddster/node-red-contrib-wemo-emulator#12]
Could the help page be extended to define the port settings required to make the emu;ator visible when running behind a firewall. After some research I found I had to open the following ports on my fedora installation to enable Alexa to discover my 'device':

`1900/udp`
`<device specific port>/tcp`

Once these two ports were opened everything worked like a charm. Thanks.

**Comment by biddster** [comment]
Great idea. I'll do it.

**Comment by biddster** [comment]
Fixed, will be included in the next release.
