### ISSUE TITLE
Problems with alexa iphone app

### ISSUE THREAD

**Issue by Toshibass** [biddster/node-red-contrib-wemo-emulator#14]
Hi I have been a long time user of your wemo-emulator and I still works fine for me however since the recent alexa update (the one that adds calling & messaging /multi room) which incidentally I didn't install yet) the ios app freezes when I try to discover devices like there is none listed in the app and when I try to discover them the screen says "This may take up to 20 seconds then does nothing else.

Is anyone seeing this ?  I am reluctant to sign up for calling & messaging as 1 - I don't think I really want it and 2 - I am worried it will screw up my working system.... the alexa web app still functions fine and I can see all my devices and find new ones.

**Comment by biddster** [comment]
Have you tried discovery by going to the https://alexa.amazon.co.uk (or equivalent for your country) in a desktop web browser?

**Comment by Toshibass** [comment]
Yes Discovery as I said "the alexa web app still functions fine.....," however just today there was another update to the ios alexa app and now Discovery works fine, so it appears to have been a problem with the app.

**I never thought it was a problem with your node**, it just unbelievable to me that you can google all day looking for other people having problems with the alexa app and find nothing but surly I cannot be the only person with these problems !

Anyway thanks for your response I'm going to close this non issue.

**Comment by biddster** [comment]
Glad it's all working ok for you now.
