### ISSUE TITLE
Two nodes appearing

### ISSUE THREAD

**Issue by martinschki** [biddster/node-red-contrib-wemo-emulator#15]
When I add a node, I have always two nodes appearing in Alexa
One is called "WeMo Switch" and the other one "Wemo Steckdose"
Alexa is on german and "Steckdose" means wall plug

**Comment by biddster** [comment]
That's not something I've seen here in the UK. Do either of the nodes actually work?

**Comment by martinschki** [comment]
Yes, but the problem is that I have to delete one of the two first in Alexa, otherwise it won’t.
Is there any way you can look into this? Can I provide logs?

**Comment by biddster** [comment]
It's likely to be a bug in the library I use to emulate wemo, this node actually does very little other than wrap that library in order to allow node red to use it. I'll see if there's any debugging we can enable.

**Comment by jonathanschneider** [comment]
I encounter the very same issue. Two devices: "WeMo Switch" and "WeMo Steckdose".

**Comment by MrPasty** [comment]
Same here - is this bug being tracked?

**Comment by biddster** [comment]
Fix released in version 1.0.0 that should sort this. Please let me know how you get on and reopen if needed.

You will get one more duplicate device after upgrading to 1.0.0, that's unavoidable unfortunately. However, you can remove all of the old duplicate devices and you should not get any more duplicates.
