### ISSUE TITLE
Strange problems on set up

### ISSUE THREAD

**Issue by frownbreaker** [biddster/node-red-contrib-wemo-emulator#16]
Hi I've installed the module for Node-Red and have set up some Wemo Emulator nodes.

I can trigger these from an Andriod app call Wemo Trigger which detects the Node-Red Wemo Emulator endpoints and can fire messaged to them. Interestingly the only inbound payload seems to be the turn off command (inspected using debug) no ON message.

The Alexa command to find new devices never yields any devices, but the third party Andriod apps sees them all the time (but can only send each endpoint a power off command).

Today I tried the Alexa home skill that links to Node-Red Skill using the Alex-AWS-Login-OAuth-Node Red and that works fine discovery and execution and I'm able to turn devices on and off.

I've not got an Echo only a FireTV stick with Alexa Voice all the automation is using ESP8266 (Web Server) proxied via Node-Red on Armbian on Orange Pi One.

**Comment by biddster** [comment]
I'm not sure why this would be, your setup seems perfectly legitimate.

Have you tried discovery a few times, others have reported that it's discovered after a few attempts?

**Comment by biddster** [comment]
1.0.0 is released and uses the latest wemore which I think will fix this. Please test and reopen this issue if necessary.
