### ISSUE TITLE
Alexa app can't control emulated devices

### ISSUE THREAD

**Issue by jonathanschneider** [biddster/node-red-contrib-wemo-emulator#17]
Controlling the emulated devices with the Echo works fine. When trying to control them through the Alexa app though it says the device doesn't respond. Is this error on Amazon or the node?

**Comment by martinschki** [comment]
Works with me
But, in my case, I get two entries in the Alexa app for one device. I then have to manually delete one before it works...

**Comment by jonathanschneider** [comment]
Weird. I only have one entry per device. Can you control the device from both entries in the Alexa app?

**Comment by martinschki** [comment]
NO, I have to delete one first 
(One entry is English and one German, my system is setup in german)

**Comment by jonathanschneider** [comment]
Maybe it’s a port/firewall issue? Which ports are you using for example?

Where does the Alexa app get the second language from in your case?

**Comment by AlGu1** [comment]
Hi,

i have also this problem and fixed it with changing the code. See [here](https://github.com/dhleong/wemore/issues/14).

Thanks for your work
AlGu

**Comment by biddster** [comment]
Thanks for the report. I wonder if this is what's causing others to see 2 devices?

**Comment by AlGu1** [comment]
I think it's only the fix for "Alexa app can't control emulated devices". Not for other bugs e.g. 2 devices. :-)

**Comment by biddster** [comment]
@AlGu1 Did you have to remove and then get alexa to rescan for devices after you changed emulate.js? Or was a node-red restart enough?

**Comment by AlGu1** [comment]
I have removed all devices in Alexa, restart node-red and then rescan. Now i can change the state in Alexa App but there is a little missing feature:
If i change the state outside of Alexa App, the Alexa App dose not get anything. I think there is no event that tells Alexa the new state?!

**Comment by biddster** [comment]
Fix released in version 1.0.0 for duplicate devices and I think it will fix this issue. Please let me know how you get on and reopen if needed.

You will get one more duplicate device after upgrading to 1.0.0, that's unavoidable unfortunately. However, you can remove all of the old duplicate devices and you should not get any more duplicates.
