### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by scargill** [biddster/node-red-contrib-wemo-emulator#2]
Hi

Well, I dropped the node into node-red - called it "thing" - it says it is listening on 39300 -   and I said to my ECHO "find devices" - it said it has found a device.  I said "Alexa turn thing on" -  and nothing - can't find it ...

Am I missing a stage here??

Pete.

**Comment by biddster** [comment]
No Pete, you're not missing anything. That's all I do with the wemo emulator.

Have you tried the alexa app and made sure it's listed under smart home devices? You can do that via the ios/droid app or here, http://alexa.amazon.co.uk/spa/index.html#smart-home.

**Comment by rlust** [comment]
How do you add the Wemo skill to Alexa?

**Comment by biddster** [comment]
@rlust it's already there, wemo support is built in. You open the Alexa app and go to smart home. Then click "discover devices".

<img width="496" alt="screen shot 2016-11-03 at 10 43 15" src="https://cloud.githubusercontent.com/assets/995967/19963016/64714ada-a1b2-11e6-8060-33f637ac3115.png">

**Comment by biddster** [comment]
I'm closing this in light of https://github.com/biddster/node-red-contrib-wemo-emulator/issues/4

Assuming this Node is working and detecting things as the above bug states that they can't be deleted.
