### ISSUE TITLE
Working with alexa sdk on raspberry as well? 

### ISSUE THREAD

**Issue by Zacki84** [biddster/node-red-contrib-wemo-emulator#23]
Hi
Does this also work when alexa sdk is running on same raspberry? Or is this like fauxmo lib which is only working with 1st gen of dot?
Thanks

**Comment by biddster** [comment]
I honestly don't know the answer to this. I've not looked at the alexa sdk stuff at all. This node simply wraps the wemore library and it's that library that handles the Alexa stuff.
