### ISSUE TITLE
Can this work with an AVS device? (Raspberry Pi)

### ISSUE THREAD

**Issue by Andergraw** [biddster/node-red-contrib-wemo-emulator#26]
First of all, thank you for your work! 
Now my question: I have been working on a RPi AVS enabled device (with official SDK) and after a lot of headaches, I discovered that neither this nor other LAN addons work with my device unless a real Alexa device is on and in the same LAN.
Would it be possible to make this plugin work locally, without linking to any Alexa skiil and with my Raspberry Pi with Alexa SDK on it?

Thanks,

**Comment by biddster** [comment]
I really don't know the answer to this. I've not looked at the alexa sdk stuff at all. This node simply wraps the wemore library and it's that library that handles the Alexa stuff.

**Comment by Andergraw** [comment]
Yeah, I supposed.
Thanks anyway, it is a nice piece of work
