### ISSUE TITLE
Deploy does not work when changes are made

### ISSUE THREAD

**Issue by Toshibass** [biddster/node-red-contrib-wemo-emulator#6]
Thanks for writing this node it works well, however once deployed, if any change is made in the node for example ... if I change On Payload from **ON** to **1** when I Deploy (choosing Full or Modified nodes) I still get the output as **ON**  only when I stop and restart node-red does the change take effect and I then get a output as **1**

**Comment by biddster** [comment]
What version of the node are you using? 0.4.0?

**Comment by Toshibass** [comment]
Yes 0.4.0

**Comment by biddster** [comment]
I'm struggling to recreate it here. What version of NodeRED are you running and what version of NodeJS?

**Comment by Toshibass** [comment]
Sorry for late reply I've been away for a few days.

Node-red v0.15.2
NodeJS v4.6.2
Dashboard v2.1.0

**Comment by biddster** [comment]
No problem, so have I!

I'll check my local setup against those versions and see what I can find.

**Comment by Toshibass** [comment]
I just want to add to this I updated to Dashboard 2.2.0 but that makes no difference, I still have to restart node-red if I change the payload on the wemo-emulator-node but lets face it its **no big deal,** because its such a rare case to change stuff once the node is setup and working as long as you remember to restart if you do ever change something.

**Comment by biddster** [comment]
Confirming fixed in 1.0.0
